import pandas as pd

# Movie data as a list of dictionaries
movie_data = [
    {'title': 'Baahubali: The Beginning', 'year': 2015, 'certificate': 'UA', 'genre': 'Action, Drama', 'overview': 'In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.', 'runtime': 159, 'rating': 8.1, 'no_of_ratings': 99114},
    {'title': 'Baahubali: The Conclusion', 'year': 2017, 'certificate': 'UA', 'genre': 'Action, Drama', 'overview': 'When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.', 'runtime': 167, 'rating': 8.2, 'no_of_ratings': 71458},
    {'title': 'Nenokkadine', 'year': 2014, 'certificate': 'U', 'genre': 'Action, Thriller', 'overview': 'A rock star must overcome his psychological inhibitions to seek revenge for his parents\' death.', 'runtime': 170, 'rating': 8.1, 'no_of_ratings': 47131},
    {'title': 'Dhoom 3', 'year': 2013, 'certificate': 'UA', 'genre': 'Action, Thriller', 'overview': 'When Sahir, a circus entertainer trained in magic and acrobatics, turns into a thief to take down a corrupt bank in Chicago that ruined his father, Indian officers Jai and Ali are called to catch him.', 'runtime': 172, 'rating': 5.4, 'no_of_ratings': 43211},
    {'title': 'Ra.One', 'year': 2011, 'certificate': 'PG', 'genre': 'Action, Adventure', 'overview': 'When the villain of an action game takes on physical form, it\'s only the game\'s less powerful protagonist who can save his creator\'s family.', 'runtime': 156, 'rating': 4.6, 'no_of_ratings': 37211},
    {'title': 'Krrish', 'year': 2006, 'certificate': 'PG', 'genre': 'Action, Sci-Fi', 'overview': 'Krrish, a superhero, sets out to save his lover from the clutches of the antagonist.', 'runtime': 152, 'rating': 6.3, 'no_of_ratings': 34450},
    {'title': 'Eega', 'year': 2012, 'certificate': 'UA', 'genre': 'Action, Drama', 'overview': 'A murdered man is reincarnated as a housefly and seeks to avenge his death.', 'runtime': 145, 'rating': 7.7, 'no_of_ratings': 32311},
    {'title': 'Krrish 3', 'year': 2013, 'certificate': 'UA', 'genre': 'Action, Sci-Fi', 'overview': 'Krrish and his scientist father have to save the world and their own family from an evil man.', 'runtime': 152, 'rating': 5.2, 'no_of_ratings': 31995},
    {'title': 'Arjun Reddy', 'year': 2017, 'certificate': 'A', 'genre': 'Drama, Romance', 'overview': 'Arjun Reddy Deshmukh, a short-tempered house surgeon gets used to drugs and drinks when his girlfriend is forced to marry another person.', 'runtime': 186, 'rating': 8.1, 'no_of_ratings': 31325},
    {'title': 'Rangasthalam', 'year': 2018, 'certificate': 'UA', 'genre': 'Action, Drama', 'overview': 'Chitti Babu begins to suspect his elder brother\'s death is not an accident.', 'runtime': 179, 'rating': 8.4, 'no_of_ratings': 30123},
    {'title': 'Ala Vaikunthapurramuloo', 'year': 2020, 'certificate': 'U', 'genre': 'Action, Drama', 'overview': 'A charming man becomes aware of his real parentage and resolves to carve a niche for himself within the family he truly belongs to.', 'runtime': 165, 'rating': 7.1, 'no_of_ratings': 16548},
    {'title': 'Awe', 'year': 2018, 'certificate': 'U', 'genre': 'Thriller', 'overview': 'A woman with multiple personality disorder takes refuge in a café that she owns.', 'runtime': 115, 'rating': 7.7, 'no_of_ratings': 10123},
    {'title': 'Geetha Govindam', 'year': 2018, 'certificate': 'UA', 'genre': 'Comedy, Romance', 'overview': 'A young teacher falls for a woman who has trust issues.', 'runtime': 142, 'rating': 7.7, 'no_of_ratings': 9935},
    {'title': 'Bharat Ane Nenu', 'year': 2018, 'certificate': 'U', 'genre': 'Action, Drama', 'overview': 'Bharat, a graduate from London becomes the chief minister of Andhra Pradesh and he tries to reform the corrupt political system.', 'runtime': 173, 'rating': 7.7, 'no_of_ratings': 9332},
    {'title': 'Rangasthalam', 'year': 2018, 'certificate': 'UA', 'genre': 'Action, Drama', 'overview': 'Chitti Babu begins to suspect his elder brother\'s death is not an accident.', 'runtime': 179, 'rating': 8.4, 'no_of_ratings': 9124},
    {'title': 'Khaidi No. 150', 'year': 2017, 'certificate': 'U', 'genre': 'Action, Comedy', 'overview': 'A man (Chiranjeevi) on the run assumes the identity of a lookalike to fight for a cause.', 'runtime': 147, 'rating': 5.6, 'no_of_ratings': 8754},
    {'title': 'Nannaku Prematho', 'year': 2016, 'certificate': 'U', 'genre': 'Action, Drama', 'overview': 'A young man sets out to avenge the death of his father.', 'runtime': 168, 'rating': 7.6, 'no_of_ratings': 8567},
    {'title': 'Mahanati', 'year': 2018, 'certificate': 'U', 'genre': 'Biography, Drama', 'overview': 'The life of South Indian actress Savitri, who took the film industry by storm in the late 1950s and became its sensation.', 'runtime': 177, 'rating': 8.5, 'no_of_ratings': 8453},
    {'title': 'Sye Raa Narasimha Reddy', 'year': 2019, 'certificate': 'U', 'genre': 'Action, Biography', 'overview': 'A biographical epic of the untold story of India\'s first freedom fighter Uyyalawada Narasimha Reddy who revolted against the atrocities of East India Company 10 years before the Sepoy Mutiny.', 'runtime': 170, 'rating': 7.7, 'no_of_ratings': 8321},
    {'title': 'Fidaa', 'year': 2017, 'certificate': 'U', 'genre': 'Romance', 'overview': 'Varun and Bhanu, both from different worlds, face challenges and try to maintain their relationship.', 'runtime': 138, 'rating': 7.5, 'no_of_ratings': 8114},
    {'title': 'Srimanthudu', 'year': 2015, 'certificate': 'U', 'genre': 'Action, Drama', 'overview': 'Harsha, a multimillionaire, attempts to rediscover the nature of humanity after he returns to his village.', 'runtime': 162, 'rating': 7.6, 'no_of_ratings': 7931},
    {'title': 'Eega', 'year': 2012, 'certificate': 'U', 'genre': 'Action, Comedy', 'overview': 'A murdered man is reincarnated as a housefly and seeks to avenge his death.', 'runtime': 145, 'rating': 7.7, 'no_of_ratings': 7523},
    {'title': 'Khaleja', 'year': 2010, 'certificate': 'U', 'genre': 'Action, Comedy', 'overview': 'The story revolves around a remote village suffering from a strange disease.', 'runtime': 170, 'rating': 7.6, 'no_of_ratings': 7115},
    {'title': 'Atharintiki Daaredi', 'year': 2013, 'certificate': 'U', 'genre': 'Action, Comedy', 'overview': 'Gautham Nanda tries to bring back his estranged family together and win back their trust.', 'runtime': 169, 'rating': 7.4, 'no_of_ratings': 6897}
]
def get_movie_data():
    return pd.DataFrame(movie_data)
